config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/kitchensink', to: 'pages#kitchensink' if Rails.env.development?

  root to: 'pages#home'
  get '/about', to: 'pages#about'

  resources :surveys, only: [:index, :new, :create, :show, :destroy] do
    resources :choices, only: [:new, :create]
    resource :publication, only: [ :create, :destroy ]
    resource :approval, only: :create
    resource :results, only: :show
    resource :reports, only: :create
  end

  resources :choices, only: :destroy do
    resources :votes, only: :create
  end

  namespace :user do
    resource :dashboard, only: :show
  end

  namespace :admin do
    resource :dashboard, only: :show
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer", as: 'blazer_dashboard'
  end
end

app/views/shared/_cookie_modal.html.erb
<div data-controller="cookie">
  <div class="modal modal--cookie is-visible" data-cookie-target="popup">
    <div class="lg:w-1/3 w-full rounded-lg shadow-lg bg-white my-3">
      <div class="flex justify-between border-b border-gray-100 px-5 py-4">
        <div class="flex items-center">
          <i class="fas fa-cookie-bite text-gradient--blue mr-2"></i>
          <h6 class="text-gray-800">We use cookies</h6>
        </div>
      </div>
      <div class="px-10 py-2 text-gray-600">
        <div style="width:100%;height:0;padding-bottom:56%;position:relative;" class="mb-4"><iframe src="https://giphy.com/embed/bAlYQOugzX9sY" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed rounded" allowFullScreen></iframe></div>
        <p class="sub-text mb-2">We use cookies and other tracking technologies to improve your browsing experience on our website, to show you personalized content, to analyze our website traffic, and to understand where our visitors are coming from.</p>
        <p class="sub-text">Agree to our <a href="<%= PRIVACY['urls']['cookies'] %>" target="_blank" class="text-gradient--blue">Cookie Policy</a> by either clicking "I agree" or closing the modal</p>
        <div class="flex w-full my-4">
          <button class="btn btn-gradient py-2 w-1/2" data-action='click->cookie#agree' data-cookie-target="agree">I agree</button>
          <button class="text-gradient--blue w-1/2" data-action='click->cookie#disagree' data-cookie-target="disagree">I disagree</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-3 rounded absolute bottom-3 right-3 z-10" role="alert">
    <span class="block sm:inline mr-8"><%= notice %></span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-yellow-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded absolute bottom-3 right-3 z-10" role="alert">
    <span class="block sm:inline mr-8"><%= alert %></span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

<% if success %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded absolute bottom-3 right-3 z-10" role="alert">
    <span class="block sm:inline mr-8"><%= success %></span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

<% if info %>
  <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded absolute bottom-3 right-3 z-10" role="alert">
    <span class="block sm:inline mr-8"><%= info %></span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-blue-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

<% if sweetalert %>
  <div class="js-fire-sweet-alert-trigger" data-message="<%= sweetalert %>"></div>
<% end %>

<% if clipboard_trigger %>
  <div class="js-fire-clipboard-copy-trigger"></div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer bg-white text-center py-4 z-10">
  <div class="footer__icons flex w-full justify-center">
    <a href="https://www.buymeacoffee.com/mangotree" class="text-4xl m-4 donation-btn" target="_blank">
      <i class="fas fa-pizza-slice text-gradient--blue"></i>
    </a>
    <a href="https://github.com/mangotreedev/reach" class="text-4xl m-4 contribute-btn" target="_blank">
      <i class="fab fa-github-alt text-gradient--blue"></i>
    </a>
    <a href="https://github.com/mangotreedev/reach/issues" class="text-4xl m-4 issue-btn" target="_blank">
      <i class="fas fa-question text-gradient--blue"></i>
    </a>
  </div>
  <div class="footer_text">
    <p class="text-black">
      A ridiculous app, built with <i class="fas fa-heart text-gradient--pink"></i> and open source.
    </p>
    <div class="footer_text__policies">
      <a href="<%= PRIVACY['urls']['terms_conditions'] %>" target="_blank" class="text-gradient--blue">Terms of Use</a> | <a href="<%= PRIVACY['urls']['privacy_policy'] %>" target="_blank" class="text-gradient--blue">Privacy Policy</a> | <a href="<%= PRIVACY['urls']['cookies'] %>" target="_blank" class="text-gradient--blue">Cookies Policy</a>
    </div>
    <h6 class="text-gradient--blue inline"><i class="far fa-copyright inline"></i>Reach</h6>
    <p class="text-black inline"> | All Rights Reserved</p>
  </div>
</div>

app/views/shared/_meta_tags.html.erb
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

app/views/shared/_navbar.html.erb
<%# TODO: Don't show white background on about page initially %>

<div class="sticky-wrapper js-nav-scroll <%= yield :background %>">
  <nav class="nav flex flex-wrap items-center justify-between px-6 py-2 w-full">
    <%= link_to about_path do %>
      <h4 class="text-gradient--blue text-shadow--light">Reach</h4>
    <% end %>
    <input class="menu-btn hidden" type="checkbox" id="menu-btn">
    <label class="menu-icon block cursor-pointer md:hidden px-2 py-4 relative select-none" for="menu-btn">
      <span class="navicon bg-grey-darkest flex items-center relative"></span>
    </label>
    <ul class="menu border-t md:border-none flex justify-end list-reset m-0 w-full md:w-auto">
      <li class="">
        <%= link_to "Random", root_path, class: "block md:inline-block sm:px-4 py-3 no-underline  text-gradient--blue"  %>
      </li>
      <li class="">
        <%= link_to "Gallery", surveys_path, class: "block md:inline-block sm:px-4 py-3 no-underline  text-gradient--blue"  %>
      </li>
      <li class="">
        <%= link_to "About", about_path, class: "block md:inline-block sm:px-4 py-3 no-underline  text-gradient--blue", data: { turbolinks: false }  %>
      </li>
      <% if user_signed_in? %>
        <li class="">
          <%= link_to "Add a Photo", new_survey_path, class: "block md:inline-block sm:px-4 py-3 no-underline text-gradient--blue"  %>
        </li>
        <li class="">
          <%= link_to "Dashboard", user_dashboard_path, class: "block md:inline-block sm:px-4 py-3 no-underline text-gradient--blue"  %>
        </li>
        <% if policy('Admin::Dashboard'.to_sym).show? %>
          <li class="">
            <%= link_to "Admin", admin_dashboard_path, class: "block md:inline-block sm:px-4 py-3 no-underline text-gradient--blue"  %>
          </li>
        <% end %>
        <li class="">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "block md:inline-block sm:px-4 py-3 no-underline text-gradient--blue"  %>
        </li>
      <% else %>
        <li class="">
          <%= link_to "Log In", new_user_session_path, class: "block md:inline-block sm:px-4 py-3 no-underline text-gradient--blue" %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

<%# TODO: Add movable background element explaining each link on the navbar, what you find with js30 %>

app/views/shared/_share_btn.html.erb
<div data-controller="clipboard">
  <i class="fas fa-share-alt text-blue-500 inline-block hover:text-blue-400 transition duration-300 cursor-pointer text-4xl ml-2 share-btn" data-action='click->clipboard#copy' data-url="<%= survey_url(survey) %>" data-clipboard-target="btn"></i>
</div>

app/views/shared/_survey_card.html.erb
<div class="survey mx-auto w-full sm:w-2/3 md:w-1/2 lg:w-2/5 py-12 relative">
  <%= inline_svg_tag "gradient_triangle.svg", class: "gradient-triangle" %>
  <%= inline_svg_tag "gradient_squiggles.svg", class: "gradient-squiggles" %>
  <div class="survey__photo relative">
    <%= cl_image_tag survey.photo.key, crop: :limit, format: :jpg, class: 'rounded-sm' %>
    <div class="survey__options-block absolute bottom-2 right-3 flex">
      <div data-controller="modal">
        <i class="fas fa-flag text-red-500 inline-block hover:text-red-400 transition duration-300 cursor-pointer text-4xl report-btn" data-action='click->modal#display'></i>
        <div class="modal" data-modal-target="popup" data-action='click->modal#overlayHide'>
          <div class="md:w-1/3 sm:w-full rounded-lg shadow-lg bg-white my-3">
            <div class="flex justify-between border-b border-gray-100 px-5 py-4">
              <div class="flex items-center">
                <i class="fa fa-exclamation-triangle text-red-500 mr-2"></i>
                <h6 class="text-gray-800">Report Photo</h6>
              </div>
              <div>
                <button><i class="fa fa-times-circle text-red-500 hover:text-red-600 transition duration-150" data-action='click->modal#hide'></i></button>
              </div>
            </div>
            <div class="px-10 py-5 text-gray-600">
              <p class="sub-text">Please remember when you report someone's post, Reach does not tell them who reported it.</p>
              <br>
              <p class="sub-text">Please provide us a little more context on why you are reporting this post:</p>
              <%= simple_form_for [@survey, Report.new] do |f| %>
                <%= f.input :reason, collection: Report.options %>
                <%= f.button :submit, "Report" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <%= render 'shared/share_btn', survey: survey %>
    </div>
  </div>

  <div class="survey__choices mt-12 mb-4 glass-card p-4">
    <% if survey.choices.empty? %>
      <h3 class="text-white mt-0 text-shadow--light">No <span class="choices-def">choices</span> added yet 😐</h3>
    <% else %>
      <h3 class="text-white mt-0 text-shadow--light">Who's the <span class="reacher-def">reacher?</span></h3>
      <div class="choices flex w-full justify-center flex-wrap">
        <% survey.choices.each do |choice| %>
          <%= link_to choice_votes_path(choice), method: :post, class: 'w-1/4 border-8 border-transparent hover:border-white' do %>
            <%= render 'choices/choice', choice: choice %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%# TODO: Add skip functionality %>