config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/kitchensink', to: 'pages#kitchensink' if Rails.env.development?

  root to: 'pages#home'
  get '/about', to: 'pages#about'

  resources :surveys, only: [:index, :new, :create, :show, :destroy] do
    resources :choices, only: [:new, :create]
    resource :publication, only: [ :create, :destroy ]
    resource :approval, only: :create
    resource :results, only: :show
    resource :reports, only: :create
  end

  resources :choices, only: :destroy do
    resources :votes, only: :create
  end

  namespace :user do
    resource :dashboard, only: :show
  end

  namespace :admin do
    resource :dashboard, only: :show
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer", as: 'blazer_dashboard'
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  has_many :choices, dependent: :destroy
  has_many :votes, through: :choices
  has_many :reports, dependent: :destroy

  has_one_attached :photo

  validates :photo, attached: true

  validates :style, presence: true

  scope :published, -> { where(published: true) }
  scope :approved, -> { where(approved: true) }
  scope :with_choices, -> { joins(:choices).uniq }

  #                   0                1
  enum style: [:one_v_one_photo, :group_photo]

  def published!
    update(published: true)
  end

  def unpublished!
    update(published: false)
  end

  def approved!
    update(approved: true)
  end

  def unapproved!
    update(approved: false)
  end

  def total_votes
    votes.count
  end

  def controversy
    # Controversy is calculated based off two factors; vote count threshold and vote standard deviation

    # Comment this back in when you have a sizable amount of surveys and votes
    return false if votes.count < 2
    variance = vote_counts.reduce(0) { |variance, x| variance += (x - mean) ** 2 }
    sigma = Math.sqrt(variance/(vote_counts.size-1))

  end

  def voted_on?(cookie)
    Survey.joins(choices: :votes).where(choices: { votes: {cookie: cookie}}).include?(self)
  end

  private

  def vote_counts
    choices.map(&:votes_count)
  end

  def mean
    vote_counts.reduce(:+) / vote_counts.length.to_f
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @surveys = policy_scope(Survey)
    case params[:filter]
    when "most"
      @surveys = @surveys.select(&:controversy).sort_by(&:controversy).first(20)
    when "least"
      @surveys = @surveys.select(&:controversy).sort_by(&:controversy).reverse!.first(20)
    when "new"
      @surveys = @surveys.order(:created_at)
    when "votes"
      @surveys = @surveys.sort_by(&:total_votes).reverse!
    when "couple"
      @surveys = @surveys.where(style: :one_v_one_photo)
    when "group"
      @surveys = @surveys.where(style: :group_photo)
    end
  end

  def new
    @survey = Survey.new
    authorize @survey
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.user = current_user
    authorize @survey
    if @survey.save
      redirect_to new_survey_choice_path(@survey)
    else
      render :new
    end
  end

  def show
    @survey = Survey.includes(:choices).find(params[:id])
    authorize @survey
    redirect_to survey_results_path(@survey) if @survey.voted_on?(@cookie)
  end

  def destroy
    @survey = Survey.find(params[:id])
    authorize @survey
    @survey.destroy!
    head :no_content
  end

  private

  def survey_params
    params.require(:survey).permit(:style, :photo)
  end
end

app/views/surveys/index.html.erb
<div class="gallery container mx-auto sm:w-full md:w-10/12 lg:w-3/4 p-4 relative">
  <%= inline_svg_tag "gradient_triangle.svg", class: "gradient-triangle" %>
  <%= inline_svg_tag "gradient_squiggles.svg", class: "gradient-squiggles" %>
  <div class="tabs flex justify-center flex-wrap my-8 mx-20 glass-card py-4">
    <%= link_to "All <i class='fas fa-th'></i>".html_safe, surveys_path, class: "text-center text-white border-4 px-4 py-2 rounded m-2 hover:opacity-50 transition duration-300 #{add_background_for(params[:filter], nil)}"%>
    <%= link_to "Most Votes <i class='fas fa-award'></i>".html_safe, surveys_path(filter: "votes"), class: "text-center text-white border-4 px-4 py-2 rounded m-2 hover:opacity-50 transition duration-300 #{add_background_for(params[:filter], 'votes')}"%>
    <%= link_to "Most Controversial <i class='fas fa-sort-amount-down'></i>".html_safe, surveys_path(filter: "most"), class: "text-center text-white border-4 px-4 py-2 rounded m-2 hover:opacity-50 transition duration-300 #{add_background_for(params[:filter], 'most')}"%>
    <%= link_to "Least Controversial <i class='fas fa-sort-amount-up'></i>".html_safe, surveys_path(filter: "least"), class: "text-center text-white border-4 px-4 py-2 rounded m-2 hover:opacity-50 transition duration-300 #{add_background_for(params[:filter], 'least')}"%>
    <%= link_to "New <i class='fas fa-fire-alt'></i>".html_safe, surveys_path(filter: "new"), class: "text-center text-white border-4 px-4 py-2 rounded m-2 hover:opacity-50 transition duration-300 #{add_background_for(params[:filter], 'new')}"%>
    <%= link_to "Couples <i class='fas fa-user-friends'></i>".html_safe, surveys_path(filter: "couple"), class: "text-center text-white border-4 px-4 py-2 rounded m-2 hover:opacity-50 transition duration-300 #{add_background_for(params[:filter], 'couple')}"%>
    <%= link_to "Groups <i class='fas fa-users'></i>".html_safe, surveys_path(filter: "group"), class: "text-center text-white border-4 px-4 py-2 rounded m-2 hover:opacity-50 transition duration-300 #{add_background_for(params[:filter], 'group')}"%>
  </div>

  <div class="surveys-masonry">
    <% @surveys.each do |survey| %>
      <div class="survey-tile">
        <%= link_to survey_path(survey) do %>
          <%= cl_image_tag survey.photo.key, crop: :fill, class: 'rounded', format: :jpg %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/surveys/new.html.erb
 <div class="add-photo-form w-full sm:w-2/3 md:w-1/2 lg:w-1/3 mx-auto mt-16">
  <%= inline_svg_tag "gradient_triangle.svg", class: "gradient-triangle" %>
  <%= inline_svg_tag "gradient_squiggles.svg", class: "gradient-squiggles" %>
  <div class="glass-card p-4 mb-24">
    <h3 class="text-white mt-0 text-shadow--light">Add a photo!</h3>
    <%= simple_form_for @survey do |f| %>
      <%= f.input :style,
            as: :radio_buttons,
            collection: Survey.styles.keys,
            legend_tag: false,
            label_method: :humanize,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper mb-6',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'}
             %>
      <div class="upload-input w-full my-2 mx-auto" data-controller="upload">
        <label for="upload_input" class="w-full text-center py-14 block cursor-pointer border-4 border-white-500 rounded border-dashed transition duration-300 text-white text-shadow--light" data-upload-target=
        "label" data-action="dragover->upload#dragIn dragleave->upload#dragOut drop->upload#dropFile">Drag a file here or <span class="text-gradient--blue">browse</span> for a file to upload</label>
        <%= f.input :photo, as: :file, label: false, input_html: { id: "upload_input", class: "hidden", data: { "upload-target": "input", "action": "click->upload#clear change->upload#changeInput" }} %>
      </div>
      <%= f.button :submit, class: "btn btn-gradient focus:outline-none w-full mt-4" %>
    <% end %>
  </div>
</div>

app/views/surveys/show.html.erb
<%= render 'shared/survey_card', survey: @survey %>