config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/kitchensink', to: 'pages#kitchensink' if Rails.env.development?

  root to: 'pages#home'
  get '/about', to: 'pages#about'

  resources :surveys, only: [:index, :new, :create, :show, :destroy] do
    resources :choices, only: [:new, :create]
    resource :publication, only: [ :create, :destroy ]
    resource :approval, only: :create
    resource :results, only: :show
    resource :reports, only: :create
  end

  resources :choices, only: :destroy do
    resources :votes, only: :create
  end

  namespace :user do
    resource :dashboard, only: :show
  end

  namespace :admin do
    resource :dashboard, only: :show
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer", as: 'blazer_dashboard'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :agree_terms, presence: true
  validates :username, uniqueness: {
    message: "%{value} is already taken!"
  }

  has_many :surveys, dependent: :destroy
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  def show
    authorize :show?, policy_class: Admin::DashboardPolicy
    @reported_surveys = Survey.where(approved: false)
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < ApplicationController
  def show
    authorize :show?, policy_class: User::DashboardPolicy
    @user_surveys = Survey.where(user: current_user)
  end
end

app/views/user/dashboards/show.html.erb
<% if @user_surveys.any? %>
  <div class="container mx-auto sm:w-full md:w-10/12 lg:w-3/4 py-12" id="user-dashboard" data-user-id="<%= current_user.id %>">
    <div class="surveys-masonry">
      <% @user_surveys.each do |survey| %>
        <div class="survey-tile rounded" data-controller="tile" data-survey=<%= survey.id %> id="<%= dom_id(survey) %>">
          <div data-controller="modal">
            <div class="survey-tile__status-block" data-tile-target="status">
              <% if !survey.approved? %>
                <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded text-red-600 bg-red-200 uppercase last:mr-0 mr-1">
                  FLAGGED
                </span>
              <% elsif !survey.published? %>
                <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded text-yellow-600 bg-yellow-200 uppercase last:mr-0 mr-1">
                  NOT PUBLISHED
                </span>
              <% else %>
                <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded text-green-600 bg-green-200 uppercase last:mr-0 mr-1">
                  LIVE: <span class="vote-count"><%= pluralize(survey.total_votes, 'vote') %></span>
                </span>
              <% end %>
            </div>
            <div class="survey-tile__removal-block">
              <button type="button" class="delete-btn" data-action='click->modal#display'>
                <i class="fas fa-times text-red-600"></i>
              </button>
            </div>
            <div class="survey-tile__options-block">
              <%= link_to '<i class="fas fa-edit text-yellow-400"></i>'.html_safe, new_survey_choice_path(survey), class: "edit-btn" %>
              <% if survey.total_votes > 0 %>
                <%= link_to '<i class="fas fa-vote-yea text-green-500"></i>'.html_safe, survey_results_path(survey), class: "results-btn" %>
              <% end %>
            </div>

            <div class="img-gradient">
              <%= cl_image_tag survey.photo.key, crop: :fill, class: "rounded", format: :jpg %>
            </div>

            <div class="modal" data-modal-target="popup" data-action='click->modal#overlayHide'>
              <div class="md:w-1/3 sm:w-full rounded-lg shadow-lg bg-white my-3">
                <div class="flex justify-between border-b border-gray-100 px-5 py-4">
                  <div class="flex items-center">
                    <i class="fa fa-exclamation-triangle text-red-500 mr-2"></i>
                    <h6 class="text-gray-800">Remove Photo</h6>
                  </div>
                  <div>
                    <button><i class="fa fa-times-circle text-red-500 hover:text-red-600 transition duration-150" data-action='click->modal#hide'></i></button>
                  </div>
                </div>
                <div class="px-10 py-5 text-gray-600">
                  <p class="sub-text">Please remember when you remove a photo, you'll also be deleting any votes cast for the photo.</p>
                  <br>

                  <% if survey.published? %>
                    <p class="sub-text">If you wish to keep the photo & results, but remove it from circulation please click below:</p>
                    <button type="button" class="my-4 py-2 text-red-500
                          rounded border border-red-500 inline-block
                          hover:bg-red-400 hover:border-red-400 hover:text-white focus:outline-none
                          transition duration-300 w-full" data-action='click->modal#hide click->tile#unpublish'>
                      Remove Photo from Circulation
                    </button>
                  <% end %>

                  <p class="sub-text">If you're sure about deleting the photo, please click below:</p>
                  <button type="button" class="my-4 py-2 bg-red-500 text-white
                        rounded border border-red-500 inline-block
                        hover:bg-red-400 hover:border-red-400 focus:outline-none
                        transition duration-300 w-full" data-action='click->modal#hide click->tile#delete'>
                    Delete Photo
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="survey mx-auto w-full sm:w-2/3 md:w-1/2 lg:w-2/5 py-12 relative">
    <%= inline_svg_tag "gradient_triangle.svg", class: "gradient-triangle" %>
    <%= inline_svg_tag "gradient_squiggles.svg", class: "gradient-squiggles" %>
    <div class="survey__photo relative">
      <%= image_tag 'works__photo_one.gif', alt: 'Confused', class: 'polaroid-border'%>
    </div>
    <div class="survey__choices mt-12 mb-4 glass-card p-4">
      <h3 class="text-white mt-0 text-shadow--light">You haven't uploaded anything yet!</h3>
      <%= link_to 'Upload a Survey', new_survey_path, class: 'btn btn-gradient focus:outline-none w-full mt-4' %>
    </div>
  </div>
<% end %>
<div class="container mx-auto sm:w-full md:w-10/12 lg:w-3/4 pb-12">
  <div class="mb-4 glass-card p-4">
    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-gradient focus:outline-none w-full' %>
  </div>
</div>