config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/kitchensink', to: 'pages#kitchensink' if Rails.env.development?

  root to: 'pages#home'
  get '/about', to: 'pages#about'

  resources :surveys, only: [:index, :new, :create, :show, :destroy] do
    resources :choices, only: [:new, :create]
    resource :publication, only: [ :create, :destroy ]
    resource :approval, only: :create
    resource :results, only: :show
    resource :reports, only: :create
  end

  resources :choices, only: :destroy do
    resources :votes, only: :create
  end

  namespace :user do
    resource :dashboard, only: :show
  end

  namespace :admin do
    resource :dashboard, only: :show
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer", as: 'blazer_dashboard'
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  def show
    authorize :show?, policy_class: Admin::DashboardPolicy
    @reported_surveys = Survey.where(approved: false)
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < ApplicationController
  def show
    authorize :show?, policy_class: User::DashboardPolicy
    @user_surveys = Survey.where(user: current_user)
  end
end

app/views/admin/dashboards/show.html.erb
<div class="container mx-auto sm:w-full md:w-10/12 lg:w-3/4 p-4">
  <% if @reported_surveys.any? %>
    <div class="surveys-masonry">
      <div data-controller="dynamic-modal">
        <div class="modal" data-dynamic-modal-target="popup" data-action='click->dynamic-modal#overlayHide' >
          <div class="md:w-1/3 sm:w-full rounded-lg shadow-lg bg-white my-3">
            <div class="flex justify-between border-b border-gray-100 px-5 py-4">
              <div class="flex items-center">
                <i class="fa fa-exclamation-triangle text-red-500 mr-2"></i>
                <h6 class="text-gray-800">Remove Photo</h6>
              </div>
              <div>
                <button><i class="fa fa-times-circle text-red-500 hover:text-red-600 transition duration-150" data-action='click->dynamic-modal#hide'></i></button>
              </div>
            </div>
            <div class="px-10 py-5 text-gray-600">
              <p class="sub-text">Please remember when you remove a photo, you'll also be deleting any votes cast for the photo.</p>
              <br>
              <p class="sub-text">If you're sure about deleting the photo, please click below:</p>
              <button type="button" class="my-4 py-2 bg-red-500 text-white
                        rounded border border-red-500 inline-block
                        hover:bg-red-400 hover:border-red-400 focus:outline-none
                        transition duration-300 w-full" data-action='click->dynamic-modal#deleteTile'>
                Delete Photo
              </button>
            </div>
          </div>
        </div>
        <% @reported_surveys.each do |survey| %>
          <div class="survey-tile" data-controller="tile" data-survey=<%= survey.id %>>
                      <div data-controller="modal">
            <div class="survey-tile__options-block">
              <button type="button" class="delete-btn" data-action='click->dynamic-modal#display'>
                <i class="fas fa-times text-red-600"></i>
              </button>

                <button type="button" class="approve-btn" data-action='click->modal#display'>
                  <i class="fas fa-check text-green-500"></i>
                </button>

            </div>
            <div class="img-gradient">
              <%= cl_image_tag survey.photo.key, crop: :fill, class: 'rounded', format: :jpg %>
            </div>
                <div class="modal" data-modal-target="popup" data-action='click->modal#overlayHide'>
                  <div class="md:w-1/3 sm:w-full rounded-lg shadow-lg bg-white my-3">
                    <div class="flex justify-between border-b border-gray-100 px-5 py-4">
                      <div class="flex items-center">
                        <i class="fa fa-check text-green-500 mr-2"></i>
                        <h6 class="text-gray-800">Publish Photo</h6>
                      </div>
                      <div>
                        <button><i class="fa fa-times-circle text-red-500 hover:text-red-600 transition duration-150" data-action='click->modal#hide'></i></button>
                      </div>
                    </div>
                    <div class="px-10 py-5 text-gray-600">
                      <p class="sub-text">Please review the reasons the photo has been reported below:</p>
                      <% survey.reports.each do |report| %>
                      <div class="flex content-center items-center my-2">
                        <i class="fas fa-exclamation-circle text-yellow-500 mr-2"></i>
                        <p class="sub-text"><%= report.reason %></p>
                      </div>

                      <% end %>
                      <br>
                      <p class="sub-text">If you feel these are not accurate, please proceed to publish the photo.</p>
                      <button type="button" class="my-4 py-2
                          rounded border border-green-500  bg-green-500 text-white inline-block
                          hover:bg-green-400 hover:border-green-400 focus:outline-none
                          transition duration-300 w-full" data-action='click->modal#hide click->tile#approve'>
                        Add Photo To Circulation
                      </button>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="mt-12 mb-4 glass-card p-4">
      <%= link_to 'Visit Blazer Dashboard', blazer_dashboard_path, class: 'btn btn-gradient focus:outline-none w-full', target: :_blank %>
    </div>
  <% else %>
    <div class="survey mx-auto w-full relative">
      <%= inline_svg_tag "gradient_triangle.svg", class: "gradient-triangle" %>
      <%= inline_svg_tag "gradient_squiggles.svg", class: "gradient-squiggles" %>
      <div class="survey__photo relative">
        <%= image_tag 'works__photo_one.gif', alt: 'Confused', class: 'polaroid-border'%>
        <h3 class="text-white mt-0 text-shadow--light text-center mt-4">No reported surveys yet!</h3>
      </div>
      <div class="survey__choices my-4 glass-card p-4">
        <%= link_to 'Visit Blazer Dashboard', blazer_dashboard_path, class: 'btn btn-gradient focus:outline-none w-full', target: :_blank %>
      </div>
    </div>
  <% end %>
</div>